plugins/gcc/options-base.js
BREAKING CHANGE: The gcc error groups are not backwards compatible with older compilers, so any projects updating the resolver will need to also update the compiler to `20171203.0.0`. This will also introduce new warnings unless `missingOverride` is added to `jscomp_off` in package gcc options.
Resolves #2.
=> Update Google Closure Compiler options for 20171203 release.

core.js, package.json, plugins/gcc/options.js, plugins/scss/index.js, resolve.js, test/utils.test.js, utils.js
This adds support for yarn workspaces, where `node_modules` may be shared at the workspace project level. A typical hierarchy for a yarn workspace would look like:
```
yarn-workspace-project
+-- node_modules (shared)
+-- workspace-dir
|   +-- project-a
|       +-- node_modules (project-a)
|   +-- project-b
|       +-- node_modules (project-b)
|   +-- project-c
\       +-- node_modules (project-c)
```
The resolver will now look at the shared `node_modules`, as well as providing projects a way to resolve modules using the [resolve](https://www.npmjs.com/package/resolve) package.
These changes are compatible with a standard npm workspace.
=> Resolve node_modules paths to support yarn workspaces.

core.js, test/utils.test.js
Ignoring symlinks was necessary for a yarn workspace workaround that has since been fixed by updating the resolver to properly detect `node_modules` folders. Removing this will allow easily changing which config/plugin projects are detected in the OpenSphere build.
This also fixes a test that would fail in a yarn workspace due to the resolved `chai` dependency being hoisted to the shared `node_modules` directory. The full path is not relevant to the test, only that it is detected and the following file detection succeeds with the same base path.
=> Detect plugins/configs from symlinks.

plugins/gcc/src.js, test/plugins/gcc/src.test.js
=> Sort goog.require statements in GCC require-all.js.

plugins/scss/index.js, test/plugins/scss/scss/should-find-bootstrap-dependency/node-sass-args, test/plugins/scss/scss/should-find-bootstrap-dependency/package.json
This makes the code a little bit more generic for resolving 3rd party SCSS files into our builds. It also adds bootstrap as an SCSS provider.
Closes #19
=> feat(bootstrap): adds support for resolving bootstrap scss

plugins/scss/index.js
Fixed issue when running resolver twice
=> fix(scss): continue if directory already exists

plugins/scss/index.js, test/plugins/scss/index.test.js
`onload` doesn’t work in Chrome/Safari for `link` elements, which makes detecting when a stylesheet is loaded a huge pain. We can hack around it by loading the same stylesheet URL in an `img` and use `onerror` to detect when the browser request completes, but that's awful and still prone to other timing problems.
This change adds a class (`.u-loaded-theme`) to each theme that can be used to detect when a theme is loaded. The `content` is set to the theme name, so the app can poll a hidden element for this style change and determine when the stylesheet is ready.
=> feat(themes): Add detection class to theme stylesheets.

plugins/scss/index.js, test/plugins/scss/index.test.js
IE and Edge dont support content in the selector (only in :before or :after). So updated to be the :before selector, then making updates to bootstrap 4 theme switch to use the :before selector
=> fix(bootstrap4): fixed theme selector for bootstrap 4 css check

package.json, plugins/electron/index.js, test/plugins/electron/electron/should-generate-electron-app-package/expected.json, test/plugins/electron/electron/should-generate-electron-app-package/opensphere-electron/app/package.json, test/plugins/electron/electron/should-generate-electron-app-package/opensphere-electron/package.json, test/plugins/electron/electron/should-generate-electron-app-package/project/package.json, test/plugins/electron/electron/should-ignore-missing-build-config/project/package.json, test/plugins/electron/electron/should-ignore-missing-electron-config/project/package.json, test/plugins/electron/electron/should-ignore-missing-electron-project/project/package.json, test/plugins/electron/index.test.js
Most dependencies for this build are packaged into the web app itself. However, Electron apps allow the use of the web app alongside typical node.js packages. Since those dependencies must be packaged by the electron-package project, we will generate an app/package.json for it to read from all the available plugins.
=> feat(electron): Add resolver for packaged electron deps

package.json, plugins/gcc/options-base.js, test/plugins/scss/scss/should-find-bootstrap-dependency/package.json
BREAKING CHANGE: Projects with Closure Compiler warnings for missingOverride or unusedPrivateMembers will need to fix those warnings before upgrading. They are now flagged as errors.
=> Move missingOverride and unusedPrivateMembers to errors

plugins/scss/index.js, test/plugins/scss/scss/should-use-extra-scss-paths/node-sass-args, test/plugins/scss/scss/should-use-extra-scss-paths/package.json
Previously package files had to cram paths into directories.scss, which is not really intended for this purpose. Now you can use build.scssPaths as an array to enumerate resolvable paths like
`package/scss`.
=> feat(scss): Resolve scss paths from build config

core.js
Fixes errors that may occur when using NPM instead of Yarn.
=> Ignore paths that do not exist.

package.json, plugins/gcc/defines.js, plugins/gcc/src.js, test/utils-find-lines/README.md, test/utils-find-lines/test.js, test/utils.test.js, utils.js
This replaces simple-grep, which does not concat the stdout buffer from multiple callbacks.
Fixes #32.
=> Add a function to find lines in files matching a pattern.

plugins/electron/index.js, test/plugins/electron/electron/should-copy-preload-scripts/opensphere-electron/app/src/preload/preload0.js, test/plugins/electron/electron/should-copy-preload-scripts/opensphere-electron/app/src/preload/preload1.js, test/plugins/electron/electron/should-copy-preload-scripts/project/package.json, test/plugins/electron/electron/should-copy-preload-scripts/project/src/preload-more.js, test/plugins/electron/electron/should-copy-preload-scripts/project/src/preload.js, test/plugins/electron/electron/should-ignore-missing-electron-project/project/package.json, test/plugins/electron/index.test.js
BREAKING CHANGE: This changes the format of the `build.electron` config.
Old config:
```
{
"electron": ["some-package"]
}
```
New config:
```
{
"electron": {
"packages": ["some-package"]
}
}
```
=> Copy preload scripts for opensphere-electron.

plugins/config/index.js, plugins/gcc/options.js, test/plugins/gcc/options.test.js, test/plugins/gcc/options/should-combine-packages-correctly/expected.json, test/plugins/gcc/options/should-combine-packages-correctly/package-after.json, test/plugins/gcc/options/should-combine-packages-correctly/package-before.json, test/plugins/gcc/options/should-combine-packages-correctly/package.json, utils.js
When GCC encounters duplicate options (like --define), the last one wins. This allows packages to control the order of their options.
=> Sort GCC options in ascending package priority.

plugins/gcc/options.js, test/plugins/gcc/options/should-combine-packages-correctly/expected.json, test/plugins/gcc/options/should-combine-packages-correctly/package-after.json, test/plugins/gcc/options/should-combine-packages-correctly/package-before.json, test/plugins/gcc/options/should-combine-packages-correctly/package.json
This ensures GCC options do not contain duplicate `define` keys. The highest priority key will be used.
=> Deduplicate GCC defines.

plugins/gcc/index.js, plugins/gcc/java-writer.js, test/plugins/gcc/index.test.js, test/plugins/gcc/java-writer.test.js
Paves the way for `opensphere-build-closure-helper` to use the JS compiler API.
=> feat(gcc): Add js_output_file to JSON compiler options.

plugins/gcc/test-writer.js
Allow using `opensphere-build-closure-helper@3.0.0` to generate test manifests.
Also restores writing the test output file to `<package>-test.min.js` instead of `<package>.min.js`.
=> Write test options to JSON

plugins/gcc/defines.js
Fixes incorrect resolution when the resolver is hoisted in a Yarn workspace, but the module is not.
=> fix(gcc): Resolve module defines relative to the project dir.

package.json, plugins/resources/index.js, test/plugins/resources/index.test.js, test/plugins/resources/should-error-on-unmatched-glob/index-template.html, test/plugins/resources/should-error-on-unmatched-glob/package.json, test/plugins/resources/should-error-on-unmatched-glob/thing.js
BREAKING CHANGE: Glob patterns specified in the resources array must now match at least one file, or the resolver will error.
=> fix(resources): Require file patterns to match something.

package.json, plugins/copy-onboarding/index.js, plugins/copy-views/index.js, plugins/resources/index.js, test/plugins/copy-onboarding/copy-onboarding.test.js, test/plugins/copy-views/copy-views.test.js, test/plugins/resources/index.test.js, test/utils.test.js, utils.js
Better support for Windows paths when used in cygwin or Git Bash. Note that you will have to `npm config set script-shell "C:\\path\\to\\bash.exe"` to the bash executable that ships with either of those. Also, `yarn run` is temporarily busted (they have a [fix on master](https://github.com/yarnpkg/yarn/pull/5851)) when using that config so you will need to use `npm run` in the meantime.
=> feat: better windows support

plugins/config/index.js, plugins/gcc/defines.js
Fixes `settings-debug.json` override paths and ROOT define paths in `gcc-args.json`.
=> Fix windows paths 2

core.js
Normalizes slashes between the `name` and `projectDir` to ensure comparisons don't incorrectly fail on Windows, and prevents an infinite loop when the module isn't found and `projectDir` reaches the root path (`/`, `C:\`, etc).
=> fix(core): fix module path detection for Windows-based builds

core.js, package.json, plugins.js, plugins/config/index.js, plugins/copy-onboarding/index.js, plugins/copy-views/index.js, plugins/electron/index.js, plugins/gcc/index.js, plugins/gcc/options.js, plugins/resources/index.js, resolve.js, test/plugins/copy-onboarding/copy-onboarding.test.js, test/plugins/copy-views/copy-views.test.js, test/plugins/resources/index.test.js, test/utils.test.js, utils.js
Plugins can now specify an updater function, which is run when the package has already been resolved once.
The resolver/updater functions now take a forth argument which is the ancestry stack (by package name).
The config and gcc options plugins use those two new features to update the results. Configs are grouped by `BASE` (0), `PLUGIN` (1000), and `CONFIG` (10000). Configs can be promoted to groups in the order `CONFIG` > `PLUGIN` > `BASE` and use the highest depth within their group. The sort value is then `explicitPriority || group - depth`.
Also used the new ancestry stack to clean up the console output.
resolves #7
Given a workspace like so (with dependencies listed):
```
opensphere
opensphere-plugin-something > somelib > opensphere
opensphere-config-test > somelib-config-test …
```
=> feat: better priority ordering for plugins

plugins/gcc/options.js, test/plugins/gcc/options/should-combine-packages-correctly/expected.json
The debug loader written out by ngageoint/opensphere-build-closure-helper uses `goog.bootstrap` on each `entry_point`, in order, to load the debug application. Plugins/libs need to be loaded before the main application or the additional features they provide may not be available when the application is bootstrapped. By flipping the order, plugins and libs will be loaded into the browser before the main application.
=> fix(gcc): sort entry_point options by descending priority

plugins/gcc/defines.js, test/plugins/gcc/defines/should-use-assigned-define/expected.json, test/plugins/gcc/defines/should-use-assigned-define/foo/bar.js, test/plugins/gcc/defines/should-use-assigned-define/package.json, test/plugins/gcc/defines/should-use-assigned-module-define/expected.json, test/plugins/gcc/defines/should-use-assigned-module-define/foo/bar.js, test/plugins/gcc/defines/should-use-assigned-module-define/package.json
The Closure library now returns the defined value in `goog.define` and no longer automatically assigns the value on `window`. This is intended to allow modules to use the define locally without polluting the window object. This fixes the `goog.define` resolver to match these assignment statements.
=> feat(gcc): use goog.defines that are assigned to a value

plugins/gcc/options-base.js, plugins/gcc/options-test.js
BREAKING CHANGE: This requires Closure Compiler 20200112.0.0, which is included with opensphere-`build-closure-helper@5.0.0`.
Related PR: https://github.com/ngageoint/opensphere-build-closure-helper/pull/17
- Replace `STRICT/LOOSE` with equivalent `PRUNE/PRUNE_LEGACY` ([commit here](https://github.com/google/closure-compiler/commit/0c8ae0ec822e89aa82f8b7604fd5a68bc30f77ea)).
- Update error groups to the latest set.
- Disable new `strictCheckTypes` and `strictMissingProperties` groups due to an abundance of errors in compiled apps. Enabling these will require a larger refactor than necessary for this update.
=> refactor(goog): update gcc args for 20200112.0.0

plugins/gcc/options-test.js, plugins/gcc/test-writer.js, test/plugins/gcc/test-writer.test.js
This PR adds `hide_warnings_for` from the `package.json` to the test options. This was added because OpenLayers references old compiler warning groups, and was introducing unnecessary warnings to the test compilation.
While working this, I realized the `test-writer` tests were incorrectly passing because `require('test-writer')` returns the same instance everywhere it is called. This meant both tests and the resolver were modifying the same instance, so the `expect` calls always passed. The module now exports a function that returns a new instance of the options on each call, and tests have been updated with current intended behavior.
We may want to do this for other options modules, but those were not addressed in this PR.
=> fix(gcc): add hide_warnings_for to gcc options for tests

plugins.js
`path.sep` is not a valid regex when on win32 (single "\")
resolves #55
=> fix(plugins): use character class for path separators

plugins/gcc/defines.js, test/plugins/gcc/index.test.js
Adds `goog.SEAL_MODULE_EXPORTS=false` for tests so that tests can more easily spy/replace/mock exported items.
=> feat(gcc): add goog.SEAL_MODULE_EXPORTS=false for tests

test/utils.test.js, utils.js
I was seeing an issue where `project > libproject > other-plugin-x` was sorting `other-plugin-x` in the plugin group even though it is being used as library here and is not a plugin of the project in question.
Instead, what I've done here is require that the group for any particular `depStack` depends on `<rootPackageName>-plugin|config-` rather than just `-plugin|config-`.
This could be marked as a breaking change as plugins or configs getting picked up by folder name but not by package name (package name doesn't match folder name) may no longer be sorted in the same order. It's really minor though so I thought I'd leave that up to review on whether to mark it as such.
=> fix(utils): only consider plugin/config of root package

plugins/config/index.js
Previously, if the key to delete was not in the object, instead of removing it (aka: do nothing), it would go through the add path and the value would become `"__delete__"`. Not good when you really just wanted to ensure that the default was used.
=> fix(config): merge delete should always delete

plugins/gcc/options.js, test/plugins/gcc/options/should-combine-packages-correctly/package-duplicates.json
GCC will error if it encounters duplicate values in array-based options, so dedupe arrays after combining options from all packages.
=> feat(gcc): dedupe arrays in gcc options

plugins/gcc/index.js, plugins/gcc/webpack-writer.js, test/plugins/gcc/json-writer.test.js, test/plugins/gcc/webpack-writer.test.js
This PR adds a webpack writer to support use of [closure-webpack-plugin](https://webpack.js.org/plugins/closure-webpack-plugin/) in OpenSphere builds.
The writer creates two files:
- JSON options object to pass to the webpack compiler plugin. All options handled internally by the webpack plugin are removed from the original GCC options generated by the resolver.
- An `index.js` file to use as the webpack `entry`. This file has `goog.require` statements for each `entry_point` from the GCC options.
Tests were added for the new webpack writer and the existing JSON writer.
=> feat(webpack): write files to support webpack builds

plugins/gcc/options-base.js, test/plugins/gcc/java-writer.test.js, test/plugins/gcc/json-writer.test.js, test/plugins/gcc/webpack-writer.test.js
Closure Compiler 20200830.0.0 removes the `useOfGoogBase` error group. This will no longer report the error in projects on an older compiler, but it is preferred that projects update to the latest version of the compiler via `opensphere-build-closure-helper@6.0.0` (ngageoint/opensphere-build-closure-helper/pull/23).
=> feat(gcc): update error groups for gcc 20200830.0.0

utils.js
Fixes duplicate input errors on Windows builds.
=> fix(utils): normalize glob paths to system path separator

plugins/gcc/src.js
This adds support for detecting Closure namespaces defined in an ES6 module using `goog.declareModuleId`.
See Closure's ES6 migration docs here for details:
https://github.com/google/closure-compiler/wiki/Migrating-from-goog.modules-to-ES6-modules
=> feat(es6): detect es6 modules using goog.declareModuleId

package.json, plugins/gcc/index.js, plugins/gcc/test-writer.js, test/plugins/gcc/test-writer.test.js, test/plugins/gcc/test-writer/should-create-test-index-with-test-dir/index-test.js, test/plugins/gcc/test-writer/should-create-test-index-with-test-dir/package.json, test/plugins/gcc/test-writer/should-create-test-index-with-test-dir/test/exclude-a.test.js, test/plugins/gcc/test-writer/should-create-test-index-with-test-dir/test/subdir/exclude-b.test.js, test/plugins/gcc/test-writer/should-not-create-test-index-without-test-dir/package.json
In support of loading ES6 modules as test dependencies, we want to bundle all dependencies with webpack. Doing so removes the need for a script/module loader, currently `karma-test-loader.js` from `opensphere-build-index`. Instead of using a loader, the dependency bundle and all tests can be loaded directly in the Karma config.
This change writes an entry point for webpack that includes all unique `goog.require` statements from test files in the base project being resolved. For the time being, this assumes ES6 modules will use `goog.declareModuleId` so they can be included with `goog.require` and `goog.module.get`. Without that call, test files would have to use `import` or `require` which I don't believe we'll be ready to support until our code is fully transitioned to ES6 modules.
=> feat(gcc): write webpack entry point for test dependencies

.eslintrc.js, package.json, yarn.lock
Updated dev dependencies to test PR builds. `husky` was not updated because v5 does not install hooks by default and requires more invasive changes that should be addressed separately.
=> build(deps): update dev dependencies

plugins/gcc/webpack-writer.js, test/plugins/gcc/webpack-writer.test.js
I mistakenly excluded `output_manifest` from the webpack GCC options, but a manifest can be useful for debugging the build.
The official option exclusion list from the [plugin docs](https://webpack.js.org/plugins/closure-webpack-plugin/) is:
```
module_resolution
output_wrapper
dependency_mode
create_source_map
module
entry_point
```
We also exclude `js` and `js_output_file` because these are controlled by the plugin, despite not being explicitly stated.
=> feat(webpack): generate output manifest in webpack build

plugins/gcc/options-base.js, yarn.lock
BREAKING CHANGE: The `missingRequire` compiler option was disabled because it introduces an abundance of errors when upgrading the compiler. This may cause projects that have not upgraded to miss errors, so they should be aware of this
when upgrading.
=> feat(gcc): update gcc options for compiler 20210406

README.md, package.json, plugins/scss/index.js, test/plugins/scss/scss/should-not-use-sass-when-node-sass/node-sass-args, test/plugins/scss/scss/should-not-use-sass-when-node-sass/package.json, test/plugins/scss/scss/should-use-sass-when-available/node-sass-args, test/plugins/scss/scss/should-use-sass-when-available/package.json, test/plugins/scss/scss/should-use-sass-when-build-scsscompiler/node-sass-args, test/plugins/scss/scss/should-use-sass-when-build-scsscompiler/package.json
Pave the way for use of `sass` in place of `node-sass`. 
Implemented in a non-breaking way
=> refactor(sass): allow sass to be used as a scss compiler

plugins/gcc/webpack-writer.js, test/plugins/gcc/webpack-writer.test.js
This goes along with ngageoint/opensphere/pull/1341 to sort the `ol.ext` entry point to the top of the generated webpack entry point, `index.js`. That entry point needs to be loaded first, so if plugins contribute entry points they previously would have been added before the main app entry points. With this change, `ol.ext` will be sorted to the top and the remaining order will be unchanged.
=> feat(ol): sort ol.ext entry point to the top if present

plugins/gcc/options-base.js
BREAKING CHANGE: The strictMissingProperties group has been enabled as an error. This did not produce additional compiler errors in OpenSphere but may impact other projects. This option enables specific type checking when referencing a property that does not exist on a specific type (but may exist on subclasses).
=> feat(gcc): update options for gcc 20210907.0.0
